# Generated by Django 4.2 on 2024-10-22 14:12

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                error_messages={
                    "unique": "A user with that phone number already exists."
                },
                max_length=128,
                region=None,
            ),
        ),
    ]
