# Generated by Django 4.2 on 2024-10-22 18:22

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_player_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                error_messages={
                    "unique": "A user with that phone number already exists."
                },
                max_length=128,
                null=True,
                region=None,
            ),
        ),
    ]
