# Generated by Django 4.2 on 2024-10-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squash_center", "0002_alter_rentalequipment_edit_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="squashcourt",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="squashcourt",
            name="price_per_hour",
            field=models.DecimalField(decimal_places=2, default=250, max_digits=6),
        ),
    ]
